version: "3.8"

services:
    web :
#         container_name : webweb
        image : web1
        container_name : webweb
        networks:
          - site2
        expose:
         - "80"
        #ports:
         #- 80:80
        depends_on:
           - mariadb
        #links:
        #  - mariadb
        volumes:
            - ./web1:/var/www/html/
        environment:
            MYSQL_HOST : mariadb
            MYSQL_USER : root
            MYSQL_ROOT_PASSWORD : "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE : "${MYSQL_DATABASE}"
            VIRTUAL_HOST: "${VIRTUAL_HOST}"
            LETSENCRYPT_HOST: "${LETSENCRYPT_HOST}"
    mariadb :
     #    container_name : dbdb
        restart: always
        image : db1
        container_name : dbdb
            #args:
              #Db_name: ""
              #Db_password: ""
        networks:
            - site2
        #links:
        expose:
                - "3306"
              #ports:
               #- 3306:3306
        volumes:
                - pfe:/var/lib/mysql
                - ../db1/setup_db:/docker-entrypoint-initdb.d
        environment:
                  MYSQL_ROOT_PASSWORD : "${MYSQL_ROOT_PASSWORD}"
                  MYSQL_DATABASE : "${MYSQL_DATABASE}"
                  CLIENT_NAME    :  "${name}"
                  CLIENT_EMAIL    :  "${email}"
                  CLIENT_PASSWORD    :  "${password}"
              #command:  bash -c  "/auto.sh ${MYSQL_DATABASE} ${MYSQL_ROOT_PASSWORD}  &&  tail -F anything" 
      
                 # - . db1/setup_db:/docker-entrypoint-initdb.d
      
volumes:
    pfe :
networks:
    site2:
     external:
      name: clientB
      
